version: '3'

services:
  neo4j_etl:
    build:
      context: ./neo4j_etl
    env_file:
      - .env

## -----------+++++---------------##

  llm_api:
    build:
      context: ./llm_api
    env_file:
      - .env
    depends_on:
      - neo4j_etl
    ports:
      - "8000:8000"

## -----------+++++---------------##
  llm_ui:
    build:
      context: ./llm_ui
    env_file:
      - .env
    depends_on:
      - llm_api
    ports:
      - "8501:8501"